### ISSUE TITLE
AWS or cloud example

### ISSUE THREAD

**Issue by kushalkolar** [kushalkolar/mesmerize-viz#16]
Make an example of this running on some cloud compute service

**Comment by EricThomson** [comment]
If we could get this working in colab before Jan 29th that would be great: the problem is colab (and all of the services) is closed source they might need to tweak some things to get it to work.

**Comment by kushalkolar** [comment]
The issue with collab right now is that they don't support python3.8 which is the minimum required for `pygfx` or `w-gpu` (forgot the details). I tried it on Saturn cloud and it didn't work. We should ask Pat if Flatiron has some resources they can allocate for the workshop, people could just be manually given a jupyterlab session.

**Comment by EricThomson** [comment]
Dang that is a pain. That's the problem with colab there isn't the flexibility you have with azure/aws.

**Comment by kushalkolar** [comment]
fpl works on flatiron cluster etc.
