### ISSUE TITLE
WrongAlgorithmExtensionError

### ISSUE THREAD

**Issue by bashsyr** [kushalkolar/mesmerize-viz#35]
I tried to install mesmerize-viz on a win 11 machine and I got all kinds on errors regarding fastplotlib not finding modules and pygfx incompatibility, I tried pulling the latest ones from the links I also tried every version combination possible and it didn't work, the last error I got is in this attached file
[Error last build.txt](https://github.com/kushalkolar/mesmerize-viz/files/13237534/Error.last.build.txt)
Now I saw that you updated some things and I was happy, I pulled the version and tried it and now I'm getting this
```
WrongAlgorithmExtensionError              Traceback (most recent call last)
File ~\mambaforge\envs\mestest\lib\site-packages\ipywidgets\widgets\interaction.py:240, in interactive.update(self, *args)
    238     value = widget.get_interact_value()
    239     self.kwargs[widget._kwarg] = value
--> 240 self.result = self.f(**self.kwargs)
    241 show_inline_matplotlib_plots()
    242 if self.auto_display and self.result is not None:

Cell In[3], line 10, in start_widget(parent_path, batch_path)
      7 tab = Tab()
      9 mcorr_container = df.mcorr.viz()
---> 10 cnmf_container = df.cnmf.viz(start_index=2)
     12 tab.children = [mcorr_container.show(), cnmf_container.show()]
     13 tab.titles = ["mcorr", "cnmf"]

File c:\users\ba81\mestest\mesmerize-viz\mesmerize_viz\_cnmf.py:1164, in CNMFDataFrameVizExtension.viz(self, start_index, temporal_data_option, image_data_options, temporal_kwargs, reset_timepoint_on_change, input_movie_kwargs, image_widget_kwargs, data_grid_kwargs)
   1088 def viz(
   1089     self,
   1090     start_index: int = None,
   (...)
   1097     data_grid_kwargs: dict = None,
   1098 ):
   1099     """
   1100     Visualize CNMF output and other data columns such as behavior video (optional).
   1101 
   (...)
   1161         Example: `image_widget_kwargs={"cmap": "viridis"}`
   1162     """
-> 1164     container = CNMFVizContainer(
   1165         dataframe=self._dataframe,
   1166         start_index=start_index,
   1167         temporal_data_option=temporal_data_option,
   1168         image_data_options=image_data_options,
   1169         temporal_kwargs=temporal_kwargs,
   1170         reset_timepoint_on_change=reset_timepoint_on_change,
   1171         input_movie_kwargs=input_movie_kwargs,
   1172         image_widget_kwargs=image_widget_kwargs,
   1173         data_grid_kwargs=data_grid_kwargs,
   1174 
   1175     )
   1177     return container

File c:\users\ba81\mestest\mesmerize-viz\mesmerize_viz\_cnmf.py:570, in CNMFVizContainer.__init__(self, dataframe, start_index, temporal_data_option, image_data_options, temporal_kwargs, reset_timepoint_on_change, input_movie_kwargs, image_widget_kwargs, data_grid_kwargs)
    566 self._component_index = 0
    568 self._cnmf_obj: CNMF = None
--> 570 data_arrays = self._get_row_data(index=start_index)
    571 self._set_data(data_arrays)
    573 self._set_params_text_area(index=start_index)

File c:\users\ba81\mestest\mesmerize-viz\mesmerize_viz\_cnmf.py:596, in CNMFVizContainer._get_row_data(self, index)
    589 def _get_row_data(self, index: int) -> Dict[str, np.ndarray]:
    590     data_mapping = get_cnmf_data_mapping(
    591         series=self._dataframe.iloc[index],
    592         input_movie_kwargs=self.input_movie_kwargs,
    593         temporal_kwargs=self.temporal_kwargs
    594     )
--> 596     temporal = data_mapping[self.temporal_data_option]()
    598     rcm = data_mapping["rcm"]()
    600     shape = rcm.shape

File c:\users\ba81\mestest\mesmerize-viz\mesmerize_viz\_cnmf.py:94, in ExtensionCallWrapper.__call__(self, *args, **kwargs)
     93 def __call__(self, *args, **kwargs):
---> 94     rval = self.func(**self.kwargs)
     96     if self.attr is not None:
     97         return getattr(rval, self.attr)

File ~\mestest\mesmerize-core\mesmerize_core\caiman_extensions\_utils.py:18, in validate.<locals>.dec.<locals>.wrapper(self, *args, **kwargs)
     16 if algo is not None:
     17     if algo not in self._series["algo"]:
---> 18         raise WrongAlgorithmExtensionError(
     19             f"<{algo}> extension called for a <{self._series.algo}> item"
     20         )
     22 if not self._series["outputs"]["success"]:
     23     tb = self._series["outputs"]["traceback"]

WrongAlgorithmExtensionError: <cnmf> extension called for a <mcorr> item
```
which doesn't look like a problem with my setup, so I though, instead of spending two days debugging I could ask you for advice.
Thank you so much for the help :)

**Comment by bashsyr** [comment]
Here are the packages in the environment:
<details>
name: mestest2
channels:
  - defaults
  - pkgs/main
  - conda-forge
dependencies:
  - _tflow_select=2.3.0
  - absl-py=2.0.0
  - aiohttp=3.8.6
  - aiosignal=1.3.1
  - anyio=4.0.0
  - aom=3.5.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.1.0
  - av=10.0.0
  - babel=2.13.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.1.0
  - blinker=1.7.0
  - blosc=1.21.5
  - bokeh=3.3.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.20.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.2
  - caiman=1.9.16
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorcet=3.0.1
  - comm=0.1.4
  - contourpy=1.1.1
  - cryptography=39.0.0
  - cycler=0.12.1
  - cytoolz=0.12.2
  - dask-core=2023.10.1
  - dav1d=1.2.0
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=6.0.0
  - flatbuffers=23.5.26
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.43.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2023.10.0
  - future=0.18.3
  - gast=0.4.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.0
  - glib-tools=2.78.0
  - google-auth=2.23.4
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.48.1
  - grpcio=1.48.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h5py=3.9.0
  - hdf5=1.14.0
  - hdmf=3.11.0
  - holoviews=1.18.0
  - icu=58.2
  - idna=3.4
  - imagecodecs-lite=2019.12.3
  - imageio=2.31.5
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.0
  - iniconfig=2.0.0
  - intel-openmp=2023.2.0
  - ipykernel=6.26.0
  - ipyparallel=8.6.1
  - ipython=8.17.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.2
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_bokeh=2.0.4
  - jupyter_client=8.5.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.9.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.7
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
  - jupyterlab_widgets=3.0.9
  - keras=2.10.0
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lazy_loader=0.3
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.1.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.1.2
  - libdeflate=1.17
  - libexpat=2.5.0
  - libffi=3.4.2
  - libglib=2.78.0
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.44.0
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - linkify-it-py=2.0.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.5.1
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib=3.8.1
  - matplotlib-base=3.8.1
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.4.0
  - mdurl=0.1.0
  - mesmerize-core=0.3.0
  - mistune=3.0.1
  - mkl=2023.2.0
  - msys2-conda-epoch=20160418
  - multidict=6.0.4
  - munkres=1.1.4
  - mypy=1.6.1
  - mypy_extensions=1.0.0
  - nbconvert=7.10.0
  - nbconvert-core=7.10.0
  - nbconvert-pandoc=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.8
  - networkx=3.2.1
  - nose=1.3.7
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numpy=1.26.0
  - oauthlib=3.2.2
  - opencv=4.6.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.1.2
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - panel=1.3.1
  - param=2.0.0
  - parso=0.8.3
  - partd=1.4.1
  - pcre2=10.40
  - peakutils=1.3.4
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pims=0.6.1
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - pluggy=1.3.0
  - prometheus_client=0.18.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - protobuf=3.20.3
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pyasn1=0.5.0
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pygments=2.16.1
  - pyjwt=2.8.0
  - pynwb=2.5.0
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pyqtgraph=0.13.3
  - pysocks=1.7.1
  - pytest=7.4.3
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.1
  - python-flatbuffers=23.5.26
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyviz_comms=3.0.0
  - pywavelets=1.4.1
  - pywin32=306
  - pywinpty=2.0.12
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole-base=5.4.4
  - qtpy=2.4.1
  - qtwebkit=5.212
  - re2=2022.06.01
  - referencing=0.30.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - rsa=4.9
  - ruamel.yaml=0.18.4
  - ruamel.yaml.clib=0.2.7
  - scikit-image=0.20.0
  - scikit-learn=1.3.2
  - scipy=1.11.3
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.5.1
  - six=1.16.0
  - slicerator=1.1.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.44.0
  - stack_data=0.6.2
  - svt-av1=1.5.0
  - tbb=2021.9.0
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.3.0
  - terminado=0.17.0
  - threadpoolctl=3.2.0
  - tifffile=2020.6.3
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.13.0
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - uc-micro-py=1.0.1
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.0.7
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wcwidth=0.2.9
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.4
  - werkzeug=3.0.1
  - wheel=0.41.3
  - widgetsnbextension=4.0.9
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.15.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - z5py=2.0.17
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - bqplot==0.12.42
      - fastplotlib==0.1.0a14
      - freetype-py==2.4.0
      - ipydatagrid==1.2.0
      - jupyter-rfb==0.4.1
      - llvmlite==0.41.1
      - nbclient==0.7.4
      - numba==0.58.1
      - py2vega==0.6.1
      - pygfx==0.1.15
      - pylinalg==0.4.1
      - pyqt6==6.6.0
      - pyqt6-qt6==6.6.0
      - pyqt6-sip==13.6.0
      - sidecar==0.7.0
      - traittypes==0.2.1
      - tslearn==0.6.2
      - uharfbuzz==0.37.3
      - voila==0.5.5
      - websockets==12.0
      - wgpu==0.11.0
</details>

**Comment by kushalkolar** [comment]
WrongAlgorithmExtensionError means you're calling the wrong algorithm
extension on a row, ex: calling a cnmf function in a mcorr row.

Also mesmerize-viz demos are a WIP, trying to get them done by early next
week.

**Comment by bashsyr** [comment]
Hi,
Thank you for your response.
I didn't specifically call anything, I just ran the app file with voila
I know the whole mesviz is still WIP, but can you maybe guide me to where can I fix this error ?

**Comment by kushalkolar** [comment]
Set the start_index as an item which was run using the algorithm that
you're calling viz on. Ex: if you're calling cnmf.viz(start_index=2), the
item at index 2 should be a cnmf item.

If you don't specify the start index it should determine it automatically.

The voila app is currently non functional, but the cnmf and mcorr examples
work.

**Comment by bashsyr** [comment]
Thank you,
I was just looking at this line rn.
I ran the whole code in a Notebook and I choose an appropriate start index.
the problem I'm facing now is different: it's looking for b,f and it doesn't accept them being None (I have 1p results), is there a way around this, or is this Visualiztion only for 2p for now ?
this is the error I'm getting 
```
File ~\mambaforge\envs\mestest2\lib\site-packages\mesmerize_core\caiman_extensions\cnmf.py:528, in CNMFExtensions.get_rcb(self)
    525 spatial = cnmf_obj.estimates.b
    526 temporal = cnmf_obj.estimates.f
--> 528 return LazyArrayRCB(spatial=spatial, temporal=temporal, frame_dims=dims)

File ~\mambaforge\envs\mestest2\lib\site-packages\mesmerize_core\arrays\_cnmf.py:34, in LazyArrayRCM.__init__(self, spatial, temporal, frame_dims)
     14 def __init__(
     15         self,
     16         spatial: np.ndarray,
     17         temporal: np.ndarray,
     18         frame_dims: Tuple[int, int],
     19 ):
     20     """
     21     Parameters
     22     ----------
   (...)
     31         
     32     """
---> 34     if spatial.shape[1] != temporal.shape[0]:
     35         raise ValueError(
     36             f"Number of temporal components provided: `{temporal.shape[0]}` "
     37             f"does not equal number of spatial components provided: `{spatial.shape[1]}`"
     38         )
     40     self._spatial = spatial

AttributeError: 'NoneType' object has no attribute 'shape'
 ```

**Comment by kushalkolar** [comment]
Lazy rcb (reconstructed background) calculation is a on my todo list.

You can visualize just the input movie and rcm for now:

viz(image_data_options=["input", "rcm"])

**Comment by kushalkolar** [comment]
closing, rcb does not yet exist for CNMFE, not sure if/when it will be done.
