### ISSUE TITLE
setting metric sliders' limits fails if it violates pre-existing min-max conditions

### ISSUE THREAD

**Issue by X4ndri** [kushalkolar/mesmerize-viz#39]
mesmerize-viz/mesmerize_viz/_cnmf.py line 224. if the metric_array min is larger than the existing default max, the widget fails. You can imagine the same if the max is lower than the default min. Easy fix using a try-except statements or conditionals.

**Comment by kushalkolar** [comment]
Are you using the latest version from main? The sliders and boxes are initialized with the range `-99,000` to `+99,999`. 

https://github.com/kushalkolar/mesmerize-viz/blob/dd83dd9a367e2b700cb519ab0ae0d922ecfb2735/mesmerize_viz/_cnmf.py#L175-L181

Unless you have infinities in the metrics, but that is really a caiman issue, there is a hacky workaround: https://github.com/kushalkolar/mesmerize-viz/issues/38

**Comment by kushalkolar** [comment]
Assuming you got around this, closing, feel free to reopen if you need help
