### ISSUE TITLE
Unable to display image correctly

### ISSUE THREAD

**Issue by Frank497** [kushalkolar/mesmerize-viz#41]
I was trying out the mcorr_cnmf demo notebook the motion correction was finished successfully. However, I have trouble with the "Visualize with mesmerize-viz!" section. I could not have the image display properly it is all black as you can see in the following screen shot. I tried resetting the contrast but it does not help. 

![螢幕擷取畫面 2024-03-04 165641](https://github.com/kushalkolar/mesmerize-viz/assets/73454537/c40ee1de-b10f-4bb6-90da-7be6045ea161)
![螢幕擷取畫面 2024-03-04 165700](https://github.com/kushalkolar/mesmerize-viz/assets/73454537/479f401f-a27f-43bc-b5b3-bf3e622b4c90)

**Comment by Frank497** [comment]
By instruction from the link you forward, I checked my GPUs that are available to WGPU, but I can't tell what went wrong. Should I just update the GPU  driver to the latest version? Or it was something else causing the display problem?
![螢幕擷取畫面 2024-03-04 173549](https://github.com/kushalkolar/mesmerize-viz/assets/73454537/575c9d8e-d30a-4f93-b866-0208016a096e)
![螢幕擷取畫面 2024-03-04 173609](https://github.com/kushalkolar/mesmerize-viz/assets/73454537/b4c6dc73-3e61-4e39-834d-4456f20c3ab3)

**Comment by kushalkolar** [comment]
yes update your drivers, the 511.23 driver is quite old now: https://www.nvidia.com/Download/driverResults.aspx/185108/en-us/

**Comment by Frank497** [comment]
The problem was solved after I updated the driver. Thank you!
