### ISSUE TITLE
Plot feature: Error bar or scale bar? 

### ISSUE THREAD

**Issue by vncntprvst** [kushalkolar/mesmerize-viz#44]
Hi,
Just a quick question: what is the bar to the left of the temporal trace? A scale bar? Or some measure of noise or std ? What variable is it based on? 
![image](https://github.com/kushalkolar/mesmerize-viz/assets/1872756/ed8e7920-2f08-400b-bdd7-99d25ee87d9d)
Thanks,
Vincent

**Comment by kushalkolar** [comment]
That's a linear selector for moving through time: https://github.com/kushalkolar/mesmerize-viz?tab=readme-ov-file#explore-components

**Comment by vncntprvst** [comment]
Ha, ok. As the bar's height is changing from trace to trace, I wasn't sure if it also meant something else. Thank you!
